name: Garmin to Google Sheets Sync

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install .
          pip install python-dotenv

      - name: Setup Folders and Files
        run: |
          mkdir -p credentials
          # Use a heredoc to ensure the JSON is written exactly as it is in secrets
          cat << 'EOF' > credentials/client_secret.json
          ${{ secrets.GOOGLE_CREDENTIALS }}
          EOF
          
          # Create the .env file for Garmin credentials
          echo "USER1_GARMIN_EMAIL=${{ secrets.GARMIN_EMAIL }}" > .env
          echo "USER1_GARMIN_PASSWORD=${{ secrets.GARMIN_PASSWORD }}" >> .env
          echo "USER1_SHEET_ID=${{ secrets.SHEET_ID }}" >> .env

      - name: Run Garmin Sync
        run: |
          python -m src.main --output 2 --profile USER1 --start $(date -d "7 days ago" +%Y-%m-%d) --end $(date +%Y-%m-%d)
