name: Garmin to Google Sheets Sync

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install .

      - name: Create Credentials Folder
        run: mkdir -p credentials

      - name: Create Google Key File
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials/client_secret.json

      - name: Run Garmin Sync
        env:
          USER1_GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          USER1_GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          USER1_SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python -m src.main --output 2 --profile USER1 --start $(date -d "7 days ago" +%Y-%m-%d) --end $(date +%Y-%m-%d)
